version: '3.8'

services:
  json-viewer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: json-viewer
    # Optional: mount local directory for file access
    # volumes:
    #   - ./data:/app/data:ro